### ISSUE TITLE
Fragments, type conditions

### ISSUE THREAD

**Issue by ruanmartinelli** [ruanmartinelli/GitHubApp#2]
Como funcionam as _type conditions_ (encontrei na internet por esse nome) nos fragments?

Por exemplo, nesse fragment [aqui](https://github.com/ruanmartinelli/GitHubApp/blob/master/src/RepositoryListItem.js#L25), quando eu digo lá `fragment x on Repository{ ...`, esse tipo `Repository` declarado diz que só posso usar esse fragment pra buscar dados em queries que retornam objetos do tipo `Repository`?

Os tipos usados nesse campo devem corresponder aos presentes no schema? (Eg. o schema da API do GitHub deve ter um tipo `Repository` declarado).

**Comment by jgcmarins** [comment]
No. What you have to do is to declare something that exists inside `Repository`. For example, let's say we have a schema for a `TodoList`. A `TodoList` type has a  property called `item`. So the right way to access it is:
```jsx
fragment TodoListItem_item on TodoList
```
`TodoList` is a `GraphQL Object` and `item` is a property of that object.

**Comment by ruanmartinelli** [comment]
Got it! Now the name "fragment" makes even more sense. :sweat_smile:
