### ISSUE TITLE
Fragments, naming convention

### ISSUE THREAD

**Issue by ruanmartinelli** [ruanmartinelli/GitHubApp#3]
Como funciona a convenção usada pra nomear fragmentos? O que os campos separados por underscore representam? [Exemplo](https://github.com/entria/ReactNavigationRelayModern/blob/master/src/UserList.js#L115).

**Comment by jgcmarins** [comment]
Answered here: https://github.com/ruanmartinelli/GitHubApp/issues/2#issuecomment-350580410
